from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class TaskType(str, Enum):
    requirement_analysis = "requirement_analysis"
    impact_analysis = "impact_analysis"
    planning = "planning"
    review = "review"
    general = "general"


class TaskStatus(str, Enum):
    pending = "pending"
    running = "running"
    completed = "completed"
    failed = "failed"


class RouteDecision(BaseModel):
    """Router Agent output describing the selected task type."""

    task_type: TaskType
    reason: str


class RetrievedItem(BaseModel):
    """A document or code snippet retrieved for task analysis."""

    source: str
    title: str
    content: str
    score: float = Field(ge=0.0, le=1.0)
    metadata: dict[str, Any] = Field(default_factory=dict)


class AnalysisResult(BaseModel):
    """Analysis Agent output for requirement and impact analysis."""

    summary: str
    risks: list[str] = Field(default_factory=list)
    impacted_areas: list[str] = Field(default_factory=list)
    assumptions: list[str] = Field(default_factory=list)


class PlanStep(BaseModel):
    """Single implementation step generated by the Planning Agent."""

    title: str
    description: str
    deliverables: list[str] = Field(default_factory=list)


class PlanningResult(BaseModel):
    """Planning Agent output containing strategy and executable steps."""

    strategy: str
    steps: list[PlanStep] = Field(default_factory=list)


class ReviewResult(BaseModel):
    """Review Agent output for completeness and reasonableness checks."""

    passed: bool
    comments: list[str] = Field(default_factory=list)
    missing_items: list[str] = Field(default_factory=list)


class TaskAnalysisResponse(BaseModel):
    """API response containing all multi-agent outputs."""

    route: RouteDecision
    retrieved_items: list[RetrievedItem]
    analysis: AnalysisResult
    plan: PlanningResult
    review: ReviewResult


class TaskRecord(BaseModel):
    """Task lifecycle record maintained by the service layer."""

    task_id: str
    requirement: str
    status: TaskStatus = TaskStatus.pending
    events: list[str] = Field(default_factory=list)
    result: TaskAnalysisResponse | None = None
    error: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
